/**
 * Seed data for PortArea + MarinaOption + MarinaPrice
 * For Gijón → La Coruña route (19 stopover points)
 */

export const PORT_AREAS = [
  {
    name: "Gijón", slug: "gijon", country: "ES", region: "Asturias",
    lat: 43.5453, lon: -5.6621, type: "major_stopover",
    description: "Major city on the Asturian coast. Excellent facilities, provisioning, crew changes. Good departure point for westbound passages.",
    arrivalSummary: "Well-protected harbor with two breakwaters. Easy approach from NE.",
    shoreSummary: "Full city services: supermarkets, restaurants, chandlery, boatyards, hospitals.",
    repairSummary: "Multiple boatyards, Volvo/Yanmar service, sailmaker, rigging.",
    provisioningSummary: "Mercadona, Carrefour, traditional market. Excellent fresh fish.",
    orcaRisk: "low",
    marinas: [
      {
        name: "Puerto Deportivo de Gijón", slug: "puerto-deportivo-gijon",
        operator: "Puerto Deportivo de Gijón S.A.", lat: 43.5453, lon: -5.6621,
        kind: "marina", website: "https://puertodeportivogijon.com",
        email: "info@puertodeportivogijon.es", phone: "+34 985 344 543", vhfCh: "09",
        shelter: "good", maxDraft: 4.0, maxLength: 24, berthCount: 728, visitorBerths: 50,
        fuel: true, water: true, electric: true, repairs: true, laundry: true,
        showers: true, toilets: true, wifi: true, securityGate: true, pumpOut: true,
        marinaHours: "Office 09:00-21:00, fuel 08:00-20:00",
        approachDescription: "Approach from N/NE. Two breakwaters protect the entrance. Main entrance faces NE, marked by Fl.G and Fl.R. Follow buoyed channel SW. Fuel dock on starboard after entrance.",
        entranceNotes: "Breakwaters visible from 2NM. Watch for fishing boats and commercial traffic.",
        waitingArea: "Wait 0.5NM N of breakwaters in >5m depth. Good holding in sand.",
        bestTideEntry: "Any state of tide. Min depth 4m at entrance.",
        swellSensitivity: "Low — well-protected by breakwaters.",
        prices: [
          { season: "low", billingPeriod: "daily", price: 28, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
          { season: "high", billingPeriod: "daily", price: 38, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
          { season: "low", billingPeriod: "monthly", price: 420, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
          { season: "high", billingPeriod: "monthly", price: 580, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
        ],
      },
    ],
  },
  {
    name: "Avilés", slug: "aviles", country: "ES", region: "Asturias",
    lat: 43.5917, lon: -5.9250, type: "medium_stopover",
    description: "River port with excellent shelter. Good marina facilities. Visit Niemeyer Center.",
    orcaRisk: "low",
    marinas: [
      {
        name: "Marina de Avilés", slug: "marina-aviles",
        lat: 43.5917, lon: -5.9250, kind: "marina",
        phone: "+34 607 810 888", email: "info@marinadeaviles.es", vhfCh: "12",
        shelter: "good", maxDraft: 4.5, maxLength: 20, berthCount: 200, visitorBerths: 20,
        fuel: true, water: true, electric: true, showers: true, toilets: true, wifi: true,
        approachDescription: "River entrance from N. Follow leading lights. Strong current on ebb.",
        entranceNotes: "Follow buoyed channel. Ebb current can run 1-2kt.",
        bestTideEntry: "Best on rising tide. Min depth 3m in channel.",
        prices: [
          { season: "low", billingPeriod: "daily", price: 22, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
          { season: "high", billingPeriod: "daily", price: 30, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
        ],
      },
    ],
  },
  {
    name: "Luarca", slug: "luarca", country: "ES", region: "Asturias",
    lat: 43.5417, lon: -6.5333, type: "medium_stopover",
    description: "Charming fishing town. Well-sheltered marina. Good overnight stop on westward passage.",
    orcaRisk: "low",
    marinas: [
      {
        name: "Puerto Deportivo de Luarca", slug: "puerto-deportivo-luarca",
        lat: 43.5417, lon: -6.5333, kind: "marina",
        phone: "+34 985 640 842", website: "https://www.puertodeluarca.es", vhfCh: "09",
        shelter: "good", maxDraft: 3.5, maxLength: 15, berthCount: 100, visitorBerths: 15,
        fuel: true, water: true, electric: true, showers: true, toilets: true, wifi: true,
        marinaHours: "Summer: 15:00-21:00 daily (weekends 09:00-21:00). Winter: weekends 09:30-18:30",
        approachDescription: "Approach from N. Enter between breakwaters (Fl.G/Fl.R). Visitor pontoon to port.",
        entranceNotes: "Narrow entrance between breakwaters. Fl.G/Fl.R lights.",
        waitingArea: "Wait 0.3NM N of entrance in >4m depth.",
        bestTideEntry: "Any state of tide. Deep entrance.",
        swellSensitivity: "Low — excellent shelter once inside.",
        prices: [
          { season: "low", billingPeriod: "daily", price: 18, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
          { season: "high", billingPeriod: "daily", price: 25, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
        ],
      },
    ],
  },
  {
    name: "Ribadeo", slug: "ribadeo", country: "ES", region: "Galicia",
    lat: 43.5350, lon: -7.0417, type: "medium_stopover",
    description: "Gateway to Galicia. Ría entrance with tidal flow. Visit Playa de las Catedrales.",
    orcaRisk: "medium", orcaNotes: "Moderate risk in Galician waters. Monitor GT Orcas app.",
    marinas: [
      {
        name: "Puerto Deportivo de Ribadeo", slug: "puerto-deportivo-ribadeo",
        lat: 43.5350, lon: -7.0417, kind: "marina",
        phone: "+34 982 131 464", vhfCh: "09",
        shelter: "good", maxDraft: 3.0, maxLength: 15, berthCount: 150, visitorBerths: 20,
        fuel: true, water: true, electric: true, showers: true, toilets: true,
        approachDescription: "Enter ría between Illa Pancha (lighthouse) and Punta de la Cruz. Follow buoyed channel SW.",
        entranceNotes: "Strong tidal current at entrance on springs (1-2kt).",
        waitingArea: "Wait 0.5NM N of Illa Pancha in >8m depth.",
        bestTideEntry: "Best HW-2 to HW+1. Avoid LW springs.",
        swellSensitivity: "Medium — ría entrance choppy in NW swell >2m.",
        prices: [
          { season: "low", billingPeriod: "daily", price: 20, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
          { season: "high", billingPeriod: "daily", price: 28, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
        ],
      },
    ],
  },
  {
    name: "Viveiro", slug: "viveiro", country: "ES", region: "Galicia",
    lat: 43.6617, lon: -7.5950, type: "medium_stopover",
    description: "Well-sheltered ría. Modern marina at Celeiro. Good base before cape rounding.",
    orcaRisk: "medium",
    marinas: [
      {
        name: "Marina Viveiro (Celeiro)", slug: "marina-viveiro-celeiro",
        lat: 43.6617, lon: -7.5950, kind: "marina",
        phone: "+34 690 604 452", website: "https://marinaviveiro.com", vhfCh: "09",
        shelter: "good", maxDraft: 3.5, maxLength: 16, berthCount: 235, visitorBerths: 30,
        fuel: true, water: true, electric: true, showers: true, toilets: true, laundry: true, wifi: true,
        marinaHours: "Mon-Sun 09:00-14:00, 16:00-20:00",
        approachDescription: "Enter Ría de Viveiro from N. Deep ría. Marina Celeiro on E side.",
        entranceNotes: "Wide ría entrance, no hazards.",
        waitingArea: "Wait in outer ría, deep water throughout.",
        bestTideEntry: "Any state of tide. Deep throughout.",
        swellSensitivity: "Very low — deep ría.",
        prices: [
          { season: "low", billingPeriod: "daily", price: 22, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
          { season: "high", billingPeriod: "daily", price: 32, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
          { season: "low", billingPeriod: "monthly", price: 350, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
          { season: "high", billingPeriod: "monthly", price: 480, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
        ],
      },
    ],
  },
  {
    name: "Cedeira", slug: "cedeira", country: "ES", region: "Galicia",
    lat: 43.6600, lon: -8.0567, type: "medium_stopover",
    description: "Safe harbor after rounding the capes. Well-sheltered ría.",
    orcaRisk: "medium",
    marinas: [
      {
        name: "Puerto Deportivo de Cedeira", slug: "puerto-deportivo-cedeira",
        lat: 43.6600, lon: -8.0567, kind: "marina",
        phone: "+34 981 480 200", vhfCh: "09",
        shelter: "good", maxDraft: 3.0, maxLength: 14, berthCount: 100, visitorBerths: 10,
        fuel: true, water: true, electric: true, showers: true, toilets: true,
        approachDescription: "Enter Ría de Cedeira from NW. Deep and well-sheltered.",
        bestTideEntry: "Any state of tide.",
        prices: [
          { season: "low", billingPeriod: "daily", price: 18, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
          { season: "high", billingPeriod: "daily", price: 24, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
        ],
      },
    ],
  },
  {
    name: "Ferrol", slug: "ferrol", country: "ES", region: "Galicia",
    lat: 43.4833, lon: -8.2333, type: "medium_stopover",
    description: "Major naval port. Excellent shelter and all facilities. Good boatyard for repairs.",
    orcaRisk: "medium",
    marinas: [
      {
        name: "Marina de Ferrol", slug: "marina-ferrol",
        lat: 43.4833, lon: -8.2333, kind: "marina",
        phone: "+34 981 336 008", website: "https://www.apfsc.es", vhfCh: "12",
        shelter: "good", maxDraft: 5.0, maxLength: 25, berthCount: 300, visitorBerths: 30,
        fuel: true, water: true, electric: true, repairs: true, showers: true, toilets: true, wifi: true,
        approachDescription: "Narrow ría entrance (400m) between Castillo de San Felipe (S) and La Palma (N). Deep water inside.",
        entranceNotes: "Watch for naval traffic. Contact VHF 12.",
        waitingArea: "Wait 0.5NM NW of entrance.",
        bestTideEntry: "Any state of tide. Deep entrance.",
        prices: [
          { season: "low", billingPeriod: "daily", price: 25, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
          { season: "high", billingPeriod: "daily", price: 35, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
          { season: "low", billingPeriod: "monthly", price: 380, loaMeters: 9.5, sourceName: "Cruiser reports", confidence: "curated" },
        ],
      },
    ],
  },
  {
    name: "La Coruña", slug: "la-coruna", country: "ES", region: "Galicia",
    lat: 43.3700, lon: -8.4000, type: "major_stopover",
    description: "Major city. Multiple marina options. Excellent provisioning, crew changes, repairs. Torre de Hércules (UNESCO).",
    arrivalSummary: "Approach past Torre de Hércules. Contact Port Control VHF 12. Large commercial port.",
    shoreSummary: "Full city services. Multiple chandleries, boatyards, Mercado de San Agustín.",
    repairSummary: "Major boatyard services: Volvo Penta, Yanmar, sailmaker, rigging, hull work.",
    orcaRisk: "medium", orcaNotes: "Moderate risk offshore. Inside harbor = safe.",
    marinas: [
      {
        name: "Marina Coruña", slug: "marina-coruna",
        operator: "Marina Coruña S.L.", lat: 43.3680, lon: -8.3950,
        kind: "marina", website: "https://www.marinacoruna.com",
        email: "info@marinacoruna.com", phone: "+34 881 920 482", vhfCh: "12",
        shelter: "good", maxDraft: 6.0, maxLength: 50, berthCount: 700, visitorBerths: 100,
        fuel: true, water: true, electric: true, repairs: true, laundry: true,
        showers: true, toilets: true, wifi: true, customs: true, securityGate: true, pumpOut: true,
        marinaHours: "24/7. Office: 09:00-21:00",
        approachDescription: "Inner harbor basin on S side. Pontoons A-H. Report on VHF 12.",
        entranceNotes: "Follow commercial channel to inner harbor. Watch for cargo traffic.",
        waitingArea: "Wait 0.5NM NW of outer harbor. Clear of shipping.",
        bestTideEntry: "Any state of tide. Deep harbor.",
        swellSensitivity: "Low — large harbor with good protection.",
        notes: "Largest marina on the route. Best for long stays, repairs, crew changes.",
        prices: [
          { season: "low", billingPeriod: "daily", price: 30, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
          { season: "high", billingPeriod: "daily", price: 42, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
          { season: "low", billingPeriod: "monthly", price: 450, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
          { season: "high", billingPeriod: "monthly", price: 650, loaMeters: 9.5, sourceName: "Marina website", confidence: "official" },
        ],
      },
      {
        name: "Real Club Náutico de La Coruña", slug: "rcn-coruna",
        operator: "Real Club Náutico", lat: 43.3650, lon: -8.4020,
        kind: "yacht_club", phone: "+34 981 117 141", vhfCh: "09",
        shelter: "good", maxDraft: 6.0, maxLength: 30, berthCount: 353, visitorBerths: 40,
        water: true, electric: true, showers: true, toilets: true, wifi: true,
        marinaHours: "Office: 09:00-14:00, 16:00-20:00",
        approachDescription: "Adjacent to Marina Coruña in the inner harbor.",
        notes: "Yacht club atmosphere. Slightly cheaper than Marina Coruña. Limited visitor berths.",
        prices: [
          { season: "low", billingPeriod: "daily", price: 25, loaMeters: 9.5, sourceName: "Club website", confidence: "curated" },
          { season: "high", billingPeriod: "daily", price: 35, loaMeters: 9.5, sourceName: "Club website", confidence: "curated" },
          { season: "low", billingPeriod: "monthly", price: 380, loaMeters: 9.5, sourceName: "Club website", confidence: "curated" },
        ],
      },
    ],
  },
  {
    name: "Sada", slug: "sada", country: "ES", region: "Galicia",
    lat: 43.3550, lon: -8.2550, type: "medium_stopover",
    description: "Growing marina in Ría de Betanzos. Alternative to La Coruña. Good provisioning.",
    orcaRisk: "medium",
    marinas: [
      {
        name: "Club Náutico de Sada", slug: "cn-sada",
        lat: 43.3550, lon: -8.2550, kind: "yacht_club",
        phone: "+34 981 620 140", website: "https://www.puertosada.com", vhfCh: "09",
        shelter: "good", maxDraft: 3.5, maxLength: 18, berthCount: 200, visitorBerths: 20,
        fuel: true, water: true, electric: true, showers: true, toilets: true,
        marinaHours: "Mon-Sat 09:00-20:00",
        approachDescription: "Enter Ría de Betanzos from NW. Marina on W side of Sada bay.",
        bestTideEntry: "Any state of tide.",
        prices: [
          { season: "low", billingPeriod: "daily", price: 20, loaMeters: 9.5, sourceName: "Club website", confidence: "curated" },
          { season: "high", billingPeriod: "daily", price: 28, loaMeters: 9.5, sourceName: "Club website", confidence: "curated" },
          { season: "low", billingPeriod: "monthly", price: 300, loaMeters: 9.5, sourceName: "Club website", confidence: "curated" },
        ],
      },
    ],
  },
];
