#!/usr/bin/env python3
"""
Build a navigable-water grid for sea routing.

Pulls EMODnet bathymetry (the free DTM) tile-by-tile via WCS, downsampled
server-side to a fixed step, and rasterises it into a compact bitmask:
  bit = 1  → navigable  (sea depth >= SAFE_DEPTH metres)
  bit = 0  → blocked    (land, or shallower than SAFE_DEPTH)

EMODnet elevation convention: negative = below sea level (depth). So a cell is
navigable when elevation <= -SAFE_DEPTH. Land (elev >= 0) and shallow water are
blocked. The route's A* search (src/lib/searoute.ts) then threads only through
navigable cells — it cannot cross land and stays in the >= SAFE_DEPTH band.

Outputs src/lib/navgrid.data.ts (base64 bitmask + metadata), imported by both
the server and the client so the same router runs everywhere (offline too).

Run: python3 scripts/build-navgrid.py
"""
import base64, heapq, json, math, os, sys, urllib.request

# Coastal bbox: A Coruña (NW) down the whole Atlantic-Iberian coast to Gibraltar.
LATMIN, LATMAX = 35.9, 43.8
LONMIN, LONMAX = -10.2, -5.2
RES = 0.005                 # ~0.5 km grid step
SAFE_DEPTH = 20.0           # metres; route stays in >= this depth
WCS = ("https://ows.emodnet-bathymetry.eu/wcs?service=WCS&version=2.0.1"
       "&request=GetCoverage&coverageId=emodnet__mean&format=image/tiff")

COLS = round((LONMAX - LONMIN) / RES)
ROWS = round((LATMAX - LATMIN) / RES)
print(f"grid {ROWS} x {COLS} = {ROWS*COLS:,} cells @ {RES}° (~{RES*60:.1f}' )", flush=True)

import numpy as np
import rasterio
from rasterio.io import MemoryFile

elev = np.full((ROWS, COLS), 9999.0, dtype=np.float32)  # 9999 = unknown → blocked

def fetch_tile(lat0, lat1, lon0, lon1, n=200):
    url = (f"{WCS}&subset=Lat({lat0},{lat1})&subset=Long({lon0},{lon1})"
           f"&SCALESIZE=i({n}),j({n})")
    for attempt in range(3):
        try:
            with urllib.request.urlopen(url, timeout=90) as r:
                return r.read()
        except Exception as e:
            if attempt == 2:
                raise
            print(f"  retry {lat0},{lon0}: {e}", flush=True)

tiles = 0
for lat_lo in range(math.floor(LATMIN), math.ceil(LATMAX)):
    for lon_lo in range(math.floor(LONMIN), math.ceil(LONMAX)):
        data = fetch_tile(lat_lo, lat_lo + 1, lon_lo, lon_lo + 1)
        with MemoryFile(data) as mf, mf.open() as ds:
            arr = ds.read(1).astype(np.float32)
            T = ds.transform
            H, W = arr.shape
            lons = T.c + (np.arange(W) + 0.5) * T.a
            lats = T.f + (np.arange(H) + 0.5) * T.e
            cidx = np.round((lons - LONMIN) / RES - 0.5).astype(int)
            ridx = np.round((LATMAX - lats) / RES - 0.5).astype(int)
            cmask = (cidx >= 0) & (cidx < COLS)
            rmask = (ridx >= 0) & (ridx < ROWS)
            if cmask.any() and rmask.any():
                ci, cc = cidx[cmask], np.where(cmask)[0]
                ri, rr = ridx[rmask], np.where(rmask)[0]
                elev[np.ix_(ri, ci)] = arr[np.ix_(rr, cc)]
        tiles += 1
        print(f"  tile {tiles}: lat {lat_lo} lon {lon_lo}", flush=True)

nav = (elev <= -SAFE_DEPTH)
print(f"navigable cells: {int(nav.sum()):,} ({100*nav.mean():.1f}%)", flush=True)

# pack bits row-major
flat = nav.flatten()
packed = np.packbits(flat)  # uint8 array, MSB-first
b64 = base64.b64encode(packed.tobytes()).decode("ascii")

meta = {"latMax": LATMAX, "lonMin": LONMIN, "res": RES,
        "rows": ROWS, "cols": COLS, "safeDepthM": SAFE_DEPTH}

out = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "navgrid.data.ts")
with open(out, "w") as f:
    f.write("// AUTO-GENERATED by scripts/build-navgrid.py — do not edit by hand.\n")
    f.write("// Navigable-water bitmask (EMODnet bathymetry, depth >= safeDepthM).\n")
    f.write(f"export const NAVGRID_META = {json.dumps(meta)} as const;\n")
    f.write(f'export const NAVGRID_B64 = "{b64}";\n')
print(f"wrote {out} ({len(b64)/1024:.0f} KB base64)", flush=True)

# ---- in-Python A* sanity check (validates data before porting to TS) ----
def navat(r, c):
    return 0 <= r < ROWS and 0 <= c < COLS and nav[r, c]

def cell(lat, lon):
    return (round((LATMAX - lat) / RES - 0.5), round((lon - LONMIN) / RES - 0.5))

def snap(r, c):
    if navat(r, c): return (r, c)
    for rad in range(1, 80):
        for dr in range(-rad, rad + 1):
            for dc in range(-rad, rad + 1):
                if max(abs(dr), abs(dc)) == rad and navat(r + dr, c + dc):
                    return (r + dr, c + dc)
    return None

def ll(r, c):
    return (LATMAX - (r + 0.5) * RES, LONMIN + (c + 0.5) * RES)

def hav(a, b):
    R = 3440.065
    dlat = math.radians(b[0]-a[0]); dlon = math.radians(b[1]-a[1])
    h = math.sin(dlat/2)**2 + math.cos(math.radians(a[0]))*math.cos(math.radians(b[0]))*math.sin(dlon/2)**2
    return R*2*math.asin(min(1, math.sqrt(h)))

def astar(start_ll, goal_ll):
    s = snap(*cell(*start_ll)); g = snap(*cell(*goal_ll))
    if not s or not g: return None
    gll = ll(*g)
    came = {}; gsc = {s: 0.0}
    pq = [(hav(ll(*s), gll), s)]
    NB = [(-1,0),(1,0),(0,-1),(0,1),(-1,-1),(-1,1),(1,-1),(1,1)]
    while pq:
        _, cur = heapq.heappop(pq)
        if cur == g:
            path = [cur]
            while cur in came: cur = came[cur]; path.append(cur)
            return [ll(*p) for p in reversed(path)]
        for dr, dc in NB:
            nr, nc = cur[0]+dr, cur[1]+dc
            if not navat(nr, nc): continue
            t = gsc[cur] + hav(ll(*cur), ll(nr, nc))
            if t < gsc.get((nr,nc), 1e18):
                gsc[(nr,nc)] = t; came[(nr,nc)] = cur
                heapq.heappush(pq, (t + hav(ll(nr,nc), gll), (nr,nc)))
    return None

for name, a, b in [("A Coruña→Vigo", (43.366,-8.389), (42.241,-8.724)),
                   ("A Coruña→Lisboa", (43.366,-8.389), (38.70,-9.42))]:
    p = astar(a, b)
    if p:
        d = sum(hav(p[i-1], p[i]) for i in range(1, len(p)))
        print(f"  A* {name}: {len(p)} cells, {d:.1f} nm, westernmost lon {min(x[1] for x in p):.3f}", flush=True)
    else:
        print(f"  A* {name}: NO PATH", flush=True)
